# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XwoB-zDNSLdUlgDAyPm_f3ZHAiTpPxvJ
"""

books={
    "author":"annie raghav",
    "book_name":"devious love",
    "cost":250,
    "type":"fan fiction"
}

friend={
    "name":"monkey",
    "age":143,
    "city":"amezon jungle"
}

merg={**books,**friend}
print(merg)